# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('weight', models.FloatField()),
                ('active', models.BooleanField(help_text='make sure only one variable per name is active')),
            ],
            options={
                'verbose_name': 'Algorithm variable',
                'verbose_name_plural': 'algorithm variables',
            },
        ),
    ]
