# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoqtool', '0004_reporturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporturl',
            name='keywords',
            field=models.CharField(max_length=250),
            preserve_default=False,
        ),
    ]
