# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 16:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seoqtool', '0005_reporturl_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='analysis',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
