# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoqtool', '0006_report_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
