# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoqtool', '0007_report_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='custom_information',
            field=models.BooleanField(default=False),
        ),
    ]
