# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoqtool', '0008_report_custom_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporturl',
            name='keywords',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
