# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seoqtool', '0009_auto_20160804_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
