# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160722_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, default='', verbose_name='About You'),
        ),
        migrations.AddField(
            model_name='user',
            name='fb_account',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_account',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_account',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
