# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160802_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone Number'),
        ),
    ]
