# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 15:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='generics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
