# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_generics'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
