# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='view_count',
        ),
    ]
