# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 20:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='areas_of_expertise',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Technical SEO', 'Technical SEO'), ('Writer/Blogger', 'Writer/Blogger'), ('Google Analytics', 'Google Analytics'), ('Link Builder', 'Link Builder'), ('SEO Training', 'SEO Training'), ('Social Media', 'Social Media')], default='', max_length=50), default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url1',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url2',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url3',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url4',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
