# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20160825_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='areas_of_expertise_other',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
