# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 21:47
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_areas_of_expertise_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('English', 'English'), ('French', 'French'), ('Spanish', 'Spanish')], default='', max_length=50), default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='languages_other',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
